### PR TITLE
Support multiple .net versions

### PR DESCRIPTION
**Pull request by sailro**
Hello ! :)

.net 6 is going to be out of maintenance soon.
.net 9 is going to be RTM soon.

So a simple PR to support multiple versions: net6, net7, net8.

This should not break existing users, and should allow new ones to use net8 directly without downloading legacy stuff.

After that, if you want (that would be great), you just need to bump the package version and submit the new nupkg that will contain all versions.

image

Thank you !

### CODE REVIEW

**Review by aaronpowell — APPROVED** [review]

**Review by aaronpowell — CHANGES_REQUESTED** [review]
Can you update the GitHub Action workflows to support the other TFM's (and we can drop .NET 7 since it's not supported)

**Review by aaronpowell — APPROVED** [review]

**Comment by sailro** [comment]
Workflow failed due to a deprecated version of the `upload-artifact`. I bumped the version to try. 
See https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/

Sorry for all the back and forth, but I'm completely blind given I have to wait for every update for a workflow approval to check the results :)

We're going to make it.

**Comment by nhuethmayr** [comment]
Hi @aaronpowell, I also need this to work 🤣 Is anything blocking? Can we help somehow?

**Comment by aaronpowell** [comment]
Ok, had a bunch of pain with the CI and package upgrades but I've finally got it to publish as v2.0.0 on NuGet.

**Comment by aaronpowell** [comment]
Ah wait, looks like I stuffed up how versions are numbered. Should be there now.

**Comment by sailro** [comment]
Thanks !

**Pull request closed without merging**
