### PR TITLE
Improve license detection accuracy

### PR DESCRIPTION
**Pull request by Bio2hazard**
### License Cache
- Added another microsoft software license link + package to the license cache.
- Added AWSSDK license + packages to the license cache. I queried the NuGet API for all packages prefixed with `AWSSDK`. I then iterated through each package, calling the registration API to find the catalog API, and called that to get information on each package. I verified that each packages owner is either `Amazon Web Services` or `Amazon.com, Inc`, that the licenseUrl is `http://aws.amazon.com/apache2.0/` and that the projectUrl starts with either `https://github.com/aws/` or `https://aws.amazon.com/`. This is all to say I did due diligence to ensure all 302 packages are legitimate and really do use Apache-2.0. [Here's the gist](https://gist.github.com/Bio2hazard/98d34f2cfe4b9846846cbad74d1883a9) 😄
- Added xunit license + packages to the license cache. The xunit license includes both Apache-2.0 and MIT, so I set the expression to `Apache-2.0 AND MIT` which to my understanding is how to handle cases like this according to SPDX docs.

### Common Licenses
- Added BSD 3, the Microsoft Software License and the Net Foundation member license to the common licenses.

#### Compare licenseUrl against known/common locations
Prior to checking github or file contents, the licenseUrl is now checked against the list of "seeAlso" urls of the spdx dataset.
When testing, I noticed many packages used `opensource.org` or `apache.org` as the licenseUrl, but the markup of the webpages prevented content matching. Since the spdx `license.json` already contains known hosted locations for the various licenses, leveraging that seems like a good idea and significantly improved detection accuracy.

At first I used direct matching, but found that many hits were missed due to minor differences in the url. For example, `Castle.Core` specifies `http://www.apache.org/licenses/LICENSE-2.0.html` while the spdx seeAlso is `https://www.apache.org/licenses/LICENSE-2.0`

To increase accuracy, I introduced a regex that trims the protocol (http/https) and the extension (.htm/.html/.txt), which worked wonders.

#### Check license of projectUrl as a fallback
I ran into this situation with [Utf8Json](https://github.com/neuecc/Utf8Json) - it specifies neither `<license>` or `<licenseUrl>` in its nuspec, but the projectUrl points to github. Since the infrastructure to fetch the license from github is already in place, it was an easy addition. This check only happens if github checking is enabled.

-------

These changes pushed detection accuracy from 50% to 90%+ for my projects. 👍 

Sorry about the code quality. I'm a c# dev and I've never touched F# before.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Thanks @Bio2hazard, it in 1.7.0 which I'm publishing a pre-release of.

**Comment by aaronpowell** [comment]
Can you test the pre-release (available here: https://github.com/aaronpowell/dotnet-delice/packages/699810). If it's all good, I'll release it as stable

**Comment by Bio2hazard** [comment]
Hi @aaronpowell , I installed `1.7.0-ci-1570828661` as a global tool and ran it over some of my projects with the various flags (github with token, github without token, check license contents, github + check license contents) and got the expected results back, so it looks good to me. 👍

Thank you for handling the PR so quickly 💯

**Comment by aaronpowell** [comment]
Thanks for submitting the PR. I only made a slight change to one method to use an Option rather than returning null 😀

**Pull request merged**
